### ISSUE TITLE
关于“模式因果（Pattern Causality）真的有用吗？”的一些讨论

### ISSUE THREAD

**Issue by lauht** [hooozen/pattern_causality#1]
大佬您好！您在**知乎**问题“模式因果（Pattern Causality）真的有用吗？”中提到您修正了因果强度的计算方式：为I(Pxt==\hat{P_xt})=1, if Pyt=\hat{P_xt}（请原谅无法发送截图）。这里是不是有个小笔误，请问右边是不是应该表示为I(Pxt==\hat{P_xt})=1, if Pxt=\hat{P_xt}？

**Comment by hooozen** [comment]
是的，这里写错了，你是对的。
如果还有其他问题欢迎继续谈论

**Comment by lauht** [comment]
好的，万分感谢！
